### ISSUE TITLE
Apache crashes when cropping image

### ISSUE THREAD

**Issue by SerikK** [krivochenko/yii2-cropper#9]
Hi. I have apache version 2.4 installed on Openserver. And when I try to crop image apache crashes and gives error POST http://yii2-starter-kit/admin/projects/uploadPhoto/ net::ERR_CONNECTION_RESET.
I have the following configuration:
<?= $form->field($model, 'avatar')->widget(Widget::className(), [
        'uploadUrl' => Url::toRoute('/projects/uploadPhoto'),
        'width' => 370,
        'height' => 290,
        'cropAreaWidth' => 370,
        'cropAreaHeight' => 290,
    ]) ?>
in ProjectsController:
public function actions()
    {
        return [
            'uploadPhoto' => [
                'class' => 'budyaga\cropper\actions\UploadAction',
                'url' => 'http://yii2-starter-kit/uploads/projects',
                'path' => '@frontend/web/uploads/projects',
            ]
        ];
    }
.htaccess on root directory
Options -Indexes
RewriteEngine on
RewriteCond %{REQUEST_URI} ^/admin/$
RewriteRule ^(admin)/$ /$1 [R=301,L]
RewriteCond %{REQUEST_URI} ^/admin
RewriteRule ^admin(/.+)?$ /backend/web/$1 [L,PT]
RewriteCond %{REQUEST_URI} ^.$
RewriteCond %{REQUEST_URI} !storage 
RewriteRule ^(.)$ /frontend/web/$1
Please, help

**Comment by mehdi-hashemi-01** [comment]
'uploadUrl' => Url::toRoute('/projects/uploadPhoto')
chane to 
'uploadUrl' =>Yii::$app->urlManager->createUrl('projects/uploadPhoto')
